FROM node:18-alpine

WORKDIR /app

# Enable corepack for pnpm
RUN corepack enable

COPY package.json pnpm-workspace.yaml ./
COPY apps/web/package.json apps/web/
COPY packages packages/

# Install dependencies
RUN pnpm install

COPY . .

WORKDIR /app/apps/web

EXPOSE 5173
CMD ["pnpm", "dev"]
